name: stay-on

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '15 16 * * *'

jobs:
  stay-on:
    runs-on: ubuntu-latest
    steps:
    - name: curl the site
      run: |
        curl https://coba-nih-2023-survey.streamlit.app/
