name: stay-on

on:
  schedule:
    - cron: '15 16 * * *'

jobs:
  stay-on:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: curl the site
      run: |
        curl https://coba-nih-2023-survey.streamlit.app
